name: 'GitHub Actions build and deploy github pages'

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md # 忽略
      - scaffolds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Log"
        env:
          CC: ${{ toJSON(github) }}
        run: echo "$CC"

      - name: Build
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: git config --global user.email ${{github.event.pusher.email}}
      - run: git config --global user.name ${{github.event.pusher.name}}
      - run: npm ci
      - run: npm run build
      - run: sh .github/workflows/deploy.sh
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
